@startuml
package "My Restaurant - menu" {
    
    actor User as u #palegreen;line:black;text:green;

    package professionals {
        actor Chef as ch
        actor Admin as a
        actor "Food Criticer" as fc
    }
    package employees {
        
        actor Waiter as w
    }
    package customer {
        actor Customer as c  
    }

    note "Version 0.1.0." as n1 

    u <|-- c
    u <|-- w
    u <|-- a
    u <|-- ch
    u <|-- fc

    usecase "Order dish" as UC0 #palegreen;line:black;text:black;
    usecase "Cancel order if status == open" as UC1 #palegreen;line:black;text:black;
    usecase "Complete the order by sending an e-mail to the waiter" as UC2 #palegreen;line:black;text:black;
    usecase "Write guestbook entries" as UC3 #palegreen;line:black;text:black;

    c --> UC0 #green;line.dashed;
    c --> UC1 #green;line.dashed;
    c --> UC2 #green;line.dashed;
    c --> UC3 #green;line.dashed;

    u --> UC0
    u --> UC1 
    u --> UC2 
    u --> UC3 
}


@enduml